project:
  type: book
  output-dir: docs

book:
  title: "Walk It Off"
  subtitle: "Or, the Hezekiah Option"
  author: "Brad Lindblad"
  date: today
  cover-image: cover2.png
  favicon: cover2.png
  chapters:
    - index.qmd
    - backstory.qmd
    - part: routine.qmd
      chapters:
        - exercise.qmd
        - breathing.qmd
        - prayer.qmd
        - diet.qmd
    - part: causenta_visits.qmd
      chapters:
        - causenta_march25.qmd
    - part: faith.qmd
    - part: data.qmd
      chapters:
        - cardio.qmd
        - strength.qmd
        - recovery.qmd

bibliography: references.bib

format:
  html:
    number-sections: false
    theme: cosmo
    author-meta: "Brad Lindblad"
  pdf:
    documentclass: scrreprt

editor: visual
execute: 
  echo: false
  warning: false

