# Preface

There's a story in the Bible about King Hezekiah being healed by God.[^index-1]

[^index-1]: 2 Kings, Chapter 20

King Hezekiah was near death, suffering from a boil (probably a dangerous infection). He asked the Lord to remember his faithfulness, to heal him from this death sentence.

And the Lord said

> I have seen your tears. Behold, I will heal you. [^index-2]

[^index-2]: 2 Kings 20:5

But, unlike many of the other cases in the Bible where Jesus or God heals someone instantaneously, God told his prophet Isaiah to have Hezekiah

> Bring a cake of figs. And let them take and lay it on the boil, that he may recover. [^index-3]

[^index-3]: 2 Kings 20:7

and King Hezekiah was healed, and lived out his allotted days in joy.

The lesson is, sometimes (maybe many times) we need to use natural means to heal; it may not always be immediate and dramatic as we wish. God is the *Lord Who Heals You (Jehova-Rapha),* [^index-4] and he will heal you in any way that he pleases!

[^index-4]: Exodus 15:23

### What this book is

Herein is the record to myself and any who find value, of my own application of figs to my physical body in a rejoined fight against cancer.
