# Routine

When you have something like cancer, you realize that whatever you were doing *when* you became sick, may have been the reason *why* you became sick. Wherever you were at physically, mentally, socially, emotionally – you need to get away from that state!

Routine is the habits that set our physical, mental, social and emotional state.

I realized early on that in order to make all the changes that I needed to make, these things had to fit into a routine that I could check off each day.

Below I outline the routine and further expand on the components in later sections.

### Weekly tasks

**Exercise & thermal exposure**

<details>

<summary>Expand for detail</summary>

asdfadf

</details>

-   6 EWOT sessions on an elliptical

    -   4 days contrast (high and low oxygen)

    -   2 days Norweigan 4x4 (VO2 max training)

-   3 days strength

    -   Sand 2.0 program sandbag workouts

-   2 cold plunge sessions, \~ 50F

-   2 Hockatt or steam room sessions

### Daily tasks

**Lymph**

<details>

<summary>Expand for detail</summary>

asdfadf

</details>

-   Rebounding or shake plate with red light therapy (10 mins)

-   Contrast showers

**Breathwork**

<details>

<summary>Expand for detail</summary>

asdfadf

</details>

-   1-3 sessions of breath work withe the Oxygen Advantage app

-   Wim Hof breathing

**Prayer**

-   Without ceasing

**Drugs**

<details>

<summary>Expand for detail</summary>

asdfadf

</details>

-   Tazverik, 800mg 2/x day

-   Ivermectin, \~80mg (1mg/kg body weight) but visual effects force me to cycle this

**Supplements**

<details>

<summary>Expand for detail</summary>

asdfadf

</details>

-   Causenta-prescribed

    -   DAO Degrade

    -   [Gut Defend](https://causenta.com/store/Gut-Defend-Probiotic-p109023222)

        -   Powerful probiotic

    -   [Hist Fx](https://causenta.com/store/HistFx-Vitamin-C-Quercetin-and-Stinging-Nettles-Leaf-p109023244)

        -   Regulates histamine response (allergies, etc)

    -   Krill Oil (DFH)

        -   To fix an imbalance in my omega-3 to omega-6 ratio

        -   Also increase levels of plasmologens (anti-cancer)

    -   Menadione (K3)

    -   [Optimum Butyrate](https://aimstore.net/products/optimumbutyrate)

        -   Supports gut health and immune function

    -   ProResolve Plus

    -   [Spore Defend](https://causenta.com/store/Spore-Defend-Probiotic-p319826021)

        -   Broad-spectrum probiotic

    -   Vitamin C

    -   Vitamin K1

        -   Testing found that I was very low here

    -   Hoxsey-like Formula

        -   Support detox and lymphatic function

    -   [Optimum Binder](https://causenta.com/store/Optimum-Binder-p541360795)

        -   Binds with toxins that are released through detox activities like EWOT and hyperthermia

    -   [Boswellia Plus](https://causenta.com/store/Boswellia-Plus-Salicin-and-Boswellia-p109023254)

        -   Prescribed for pain, also has anti-cancer effects

-   My own research

    -   Vitamin D3 with K2

    -   Nanolite xxxx

    -   Curcumin/turmeric